import paramiko
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('172.28.10.2', username='root', password='feng1021', timeout=30)
stdin, stdout, stderr = ssh.exec_command('docker exec worklog sh -c \'ls -la /app/frontend-web/dist/assets/ | head -5\'')
print(stdout.read().decode())
stdin, stdout, stderr = ssh.exec_command('docker exec worklog sh -c \'wc -c /app/frontend-web/dist/assets/index-BGytjMR1.js\'')
print('index.js大小:', stdout.read().decode().strip())
stdin, stdout, stderr = ssh.exec_command('docker exec worklog sh -c \'grep -c "expense_items" /app/frontend-web/dist/assets/index-BGytjMR1.js\'')
print('expense_items出现次数:', stdout.read().decode().strip())
stdin, stdout, stderr = ssh.exec_command('docker exec worklog sh -c \'grep -c "totalExpenseAmount" /app/frontend-web/dist/assets/index-BGytjMR1.js\'')
print('totalExpenseAmount出现次数:', stdout.read().decode().strip())
stdin, stdout, stderr = ssh.exec_command('docker exec worklog sh -c \'grep -c "addExpenseItem" /app/frontend-web/dist/assets/index-BGytjMR1.js\'')
print('addExpenseItem出现次数:', stdout.read().decode().strip())
ssh.close()
